### ISSUE TITLE
Dependency on lava should again be on lava tip

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava-dnf#12]
We should probably switch back to depending on the tip of Lava rather than version 0.2.0.

Or is there a better way of getting around that with every release, @mgkwill ?

**Comment by bamsumit** [comment]
Do we want to do this? Keeping the dependency on tagged artifact would make the lava dependency on somewhat stable version of Lava.
We can still check validity with lava tip with `python -m unittest` with latest lava locally. That would also help us track when compatibility breaks.

**Comment by mgkwill** [comment]
> Do we want to do this? Keeping the dependency on tagged artifact would make the lava dependency on somewhat stable version of Lava. We can still check validity with lava tip with `python -m unittest` with latest lava locally. That would also help us track when compatibility breaks.

I agree with @bamsumit I think we should always depend on a stable version, for all the reasons he listed. Why do you want to depend on the latest change in lava?

We can add a conditional CI jobs that run on tip that we could activate with a comment or something like that. Also locally we should be testing against tip.

**Comment by mathisrichter** [comment]
Yes, I agree in general. But Lava is changing rapidly at the moment and keeping the dependency on a tagged artifact will break CI/CD checks of pull requests as soon as Lava changes.

For instance, the interface of the `Monitor` process will change as soon as we merge PR#128 and we would have to change lava-dnf accordingly. We could keep working with a dependence on lava 0.2.0 but at some point we would have to update the dependence to something more recent.

**Comment by mgkwill** [comment]
> Yes, I agree in general. But Lava is changing rapidly at the moment and keeping the dependency on a tagged artifact will break CI/CD checks of pull requests as soon as Lava changes.
> 
> For instance, the interface of the `Monitor` process will change as soon as we merge PR#128 and we would have to change lava-dnf accordingly. We could keep working with a dependence on lava 0.2.0 but at some point we would have to update the dependence to something more recent.

I guess the thing we really need to ensure is that each release of lava-dnf is based on a specific released version of lava and thus we need to switch this from tip to tag/dist.tar.gz at each release.

In between I guess this could be set to track tip of lava, but this will be messy in the long run. Any breaking change in lava will break lava-dnf CI. This is good in showing what needs to be updated in lava-dnf for compatibility but could be very disruptive for developing in lava-dnf. Also this breaking change would hamper fast feedback principle of DevOps. 

In the future we should consider moving separately from lava. I.E. base all work on a specific version of lava that exists now for patches on tip of lava-dnf. That would obviously mean advanced planning for lava for work that needs to be released for lava-dnf to then release later and would necessitate staggered rather than parallel releases.

**Comment by bamsumit** [comment]
I think we should do a out of phase release of Lava and Lava-libraries. Then we will get 1 week after lava release to keep up/fix the breaking changes in Lava-libraries.

I don't mind pointing to the Lava-tip for now.

**Comment by PhilippPlank** [comment]
I think for current development (internal and external) it just makes sense to depend on the latest lava version. Many new features will probably be co-developed in both repositories and lava will most likely also change quite a bit over the next months, potentially breaking many libraries.

I also think we will keep the releases in sync for the near future to not spam our users with little releases of each library.

Everything else makes in my opinion sense once we reach a lava 1.0 with the core features in place.

**Comment by mathisrichter** [comment]
@awintel Any thoughts on this?

**Comment by awintel** [comment]
What about this relatively simple release process:

- Right now, we version our SW like v_x.y.z. Going forward, we do not have to spam users for every little z-level release with a release note email notification. We'll just do this for y-level releases. That way we can create new tagged versions whenever we feel it's worthwhile to push out some improvements to users without making a big deal out of it.
- Each release of a dependent algorithm library should only depend on a fixed tagged version of any other library to avoid instability. Mostly our algorithm libraries will just depend on /lava but that might change. In addition, I assume that many people would want to install multiple libraries at the same time. Therefore all dependent libraries should agree to depend on the same tagged version of /lava or each other.
- After a release the head of /lava will advance. We might even create new tagged versions of /lava. That should not automatically impact any dependent libraries because they depend on the same old tagged /lava version as the head of those dependent classes evolves. 
- If people just want /lava, they can install the latest tagged version or even clone the head. If people want any of the algorithm libraries they will probably get an older tagged versions of /lava. I assume our package management system can take care of it, otherwise our release notes or install instructions should spell out which version to install that are compatible with each other.
- At some time, we will reach a point when an algorithm library can no longer advance without depending on another /lava version. At that point we could update the install instructions or package management system. However, this could lead to conflicts, if one algo lib advances but not another in case the /lava change is not backwards compatible. In this case, installing all algo libs (either head or or a tagged version) would result in different conflicting requirements on /lava. This should be avoided.
- If one dependent repo needs to advance we have two options: a) If the changes in /lava are backwards compatible, then we just advance the dependency of all dependent repos on a common denominator. b) I the changes in /lava are not backwards compatible, then we need some coordination between the different dependent repos.

Would such coordination be acceptable? 

Going forward I do not see us doing biweekly releases anymore. So that should give us room for such coordination.

**Comment by mathisrichter** [comment]
Yes, this is all fine. It seems to imply, however, that we build our daily development of libraries like lava-dnf against the latest tagged version rather than the tip of the repository. This may not always be possible, in particular if we want to make use of new features or bug fixes before Lava has been tagged again. As mentioned in the discussion above, this may be difficult as Lava is rapidly developing now. We can try this approach for now, though.
